### PR TITLE
on_war_relation added and create_ship scoping.

### PR DESCRIPTION
**Pull request by Alpinia**

### CODE REVIEW

**Comment by Yard1** [comment]
Shouldn't it be both a tag and a scope? Or is the former not working at all?

**Comment by Alpinia** [comment]
Using scope[country] didn't cause errors for both TAG and FROM, while using enum[country_tags] caused a error when using FROM in the effect.

**Comment by Yard1** [comment]
> Using scope[country] didn't cause errors for both TAG and FROM, while using enum[country_tags] caused a error when using FROM in the effect.

It should be both, then. Like this:
```
	## cardinality = 0..1
	creator = enum[country_tags]
	creator = scope[country]
```

**Comment by Alpinia** [comment]
Oops, I didn't know that. Added it back.

**Comment by Yard1** [comment]
Blep, in fact, it should be:
```
	## cardinality = 0..1
	creator = enum[country_tags]
	## cardinality = 0..1
	creator = scope[country]
```
Apologies

**Pull request merged**
